# Generated by Django 5.1 on 2024-08-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_affilate"),
    ]

    operations = [
        migrations.CreateModel(
            name="Builder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("buyer", "Are you a buyer?"),
                            ("broker", "Are you a broker?"),
                        ],
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("number", models.CharField(max_length=15)),
            ],
        ),
    ]
