# Generated by Django 5.1 on 2024-08-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_builder"),
    ]

    operations = [
        migrations.CreateModel(
            name="Details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("contact_number", models.CharField(max_length=20)),
                ("rera_number", models.CharField(blank=True, max_length=50, null=True)),
                ("location", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
