# Generated by Django 5.1 on 2024-08-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_details"),
    ]

    operations = [
        migrations.CreateModel(
            name="Career",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255)),
                ("number", models.CharField(max_length=15)),
                ("city", models.CharField(max_length=100)),
                (
                    "position",
                    models.CharField(
                        default="Site Head", editable=False, max_length=100
                    ),
                ),
                ("resume", models.FileField(upload_to="resumes/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
